name: Generate Android Development APK
on: [push, pull_request]
jobs:
  prepare_tools:
    name: Prepare tools to generate the APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Create site-config.ts
        run: "echo $SITE_CONFIG > src/configs/site-config.ts"
        env:
          SITE_CONFIG: ${{ secrets.SITE_CONFIG }}

      - name: Build UI
        run: npm install -g @ionic/cli yarn && yarn install && yarn build --prod

      - name: Prepare Android
        run: npx cap add android && npx cap sync

      - name: Prepare Gradle
        run: cd android && chmod +x ./gradlew && cd ..

      - name: Copy generated assets from Ionic to Capacitor Android platform
        run: npx cap copy android && npx cap update android

      - name: Build Android APK
        run: cd android && ./gradlew assembleDebug && cd ..

      - name: Uploading Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: android/app/build/outputs/apk/debug/app-debug.apk
